export const items = [
    {
      id: 1,
      url: require("../../assets/images/1.png"),
      school: "School:  University of Maryland, College Park",
      major: "Major: Chemistry",
      song: "Favorite Song:   林志炫<浮誇>",
      description: "嗨嗨～我是 Olie/歐莉，很高興認識大家～我平常喜歡跑步登山和拍照或賴在家裡睡午覺，目前下一階段想培養的興趣是挑戰高空彈跳，歡迎大家把我/被我拖出去玩XD",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 2,
      url: require("../../assets/images/2.png"),
      school: "School:  The Catholic University of America",
      major: "Major: Computer Science",
      song: "Favorite Song:   蔡依林<第三人稱>",
      description: "希望能在學聯與大家一起創造美好的回憶😊",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 3,
      url: require("../../assets/images/3.png"),
      school: "School:  American University",
      major: "Major: Public Administration",
      song: "Favorite Song:   Easy<Peasy>",
      description: "哈囉~!! 我是台南人，吃吃喝喝的行程是我的日常，但是生活除了美食，還有豐富自己的生活，所以加入學聯不僅能夠增進留學生的感情，還能為各位服務，讓學生能有一個資源共享的平台。",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 4,
      url: require("../../assets/images/4.png"),
      school: "School:  Georgetown University",
      major: "Major: Data Science in Public Policy",
      song: "Favorite Song:   蘇打綠/魚丁糸<無眠>",
      description: "喜歡爬步道、看新風景、吃美食，但也喜歡宅在家看劇。最近在探索新餐廳、咖啡廳，歡迎大家推薦～很開心加入學聯，希望跟大家一起變熟、一起成長！",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 5,
      url: require("../../assets/images/5.png"),
      school: "School:  Johns Hopkins University",
      major: "Major: Biotechnology",
      song: "Favorite Song:   陳奕迅<十年>",
      description: "哈囉！說實在的，我真的是誤打誤撞的申請，然後誤打誤撞的加入學聯會呢 ʅ（◞‿◟）ʃ  有點意外又榮幸地被選為這個大家庭的一份子。之前有相關的社團經驗但是從來沒辦過跨校的活動，所以其實蠻緊張的。期待這一年會遇到新的挑戰也很期待認識各式各樣的新朋友！ 平常喜歡旅遊、爬山、做飯烘焙、看夕陽（嗯，就是老人生活）然後最近又開始打羽毛球了～ 如果有任何同好人士的話，約起來一起玩！啊還有！很想趕快財富自由，提早退休，環遊世界🤞 ",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 6,
      url: require("../../assets/images/6.png"),
      school: "School:  University of Maryland, College Park",
      major: "Major: Aerospace Engineering",
      song: "Favorite Song:   草東沒有派對<山海>",
      description: "嗨嗨大家好，我是陳誼軒，其實我很宅，但為了身體健康，還是會出門慢跑，身體健康第一！",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 7,
      url: require("../../assets/images/7.png"),
      school: "School:  George Washington University",
      major: "Major: Business Analytics and Accountancy ",
      song: "Favorite Song:   謝震廷<你的行李>",
      description: "嗨嗨，我叫Maryanne。平常我喜歡嘗試各種運動、爬山、探索新地方，還有看房子！很期待在學聯認識大家。",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 8,
      url: require("../../assets/images/8.png"),
      school: "School:  George Washington University",
      major: "Major: Master Science in Management",
      song: "Favorite Song:   蛋堡<史詩>",
      description: "Recently I'm obsessed with TV series and stand-up comedy.(Breaking Bad, Better call Saul, Conan O'Brien needs a friend etc.) So if you wanna share any kinda idea or thought with me. It's my pleasure, then.I just started my LinkedIn journey, here is my profile link:www.linkedin.com/in/po-chun-huang-9a9876232 I really wish we can communicate with each other in business area someday! If you are willing to, you can connect with me!",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
      out: "https://www.linkedin.com/in/po-chun-huang-9a9876232",
      out_name: "linkIn"
    },
    {
      id: 9,
      url: require("../../assets/images/9.png"),
      school: "School:  University of Cambridge",
      major: "Major: Biochemistry",
      song: "Favorite Song:   陳奕迅<Shall we talk>",
      description: "是位熱愛生活、勇於挑戰的資深維州居民（自己講）。也是被生化學界耽誤了的小小飛行員👨‍🔬🧑‍✈️。在學聯最重要的工作就是為大家找錢、錢、還有錢💰今年會努力把活動辦好，讓各位有愉快難忘的一年。",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
      // out: "https://www.linkedin.com/in/daniel-huang-2468a3155/",
      // out_name: "linkIn"
    },
    {
      id: 10,
      url: require("../../assets/images/10.png"),
      school: "School:  University of Maryland, College Park",
      major: "Major: Computer Engineering ",
      song: "Favorite Song:   林宥嘉<說謊>",
      description: "嗨～大家好 我叫Daniel 我喜歡出去玩，打遊戲，拉大提琴，再請大家多多關照啦～",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
      out: "https://www.linkedin.com/in/daniel-huang-2468a3155/",
      out_name: "linkIn"
    },
    {
      id: 11,
      url: require("../../assets/images/11.png"),
      school: "School:  Virginia Tech",
      major: "Major: Computer Science",
      song: "Favorite Song:   Leo王<陪妳過假日>",
      description: "Mike is a master's student at Virginia Tech, specializing in web development and product management. Holding a master's degree in computer science, he excels in supply chain logistics, large-scale applications, and banking technology. Mike's expertise empowers him to identify and enhance technical solutions effectively. Beyond his academic pursuits, Mike enjoys hiking and working out. He eagerly anticipates leveraging his skills and enthusiasm to drive positive changes in the realm of tech innovation.",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
      out: "https://www.linkedin.com/in/hc-mike-l",
      out_name: "linkIn"
    },
    {
      id: 12,
      url: require("../../assets/images/12.png"),
      school: "School:  American Univeristy",
      major: "Major: Data Science",
      song: "Favorite Song:   周杰倫<軌跡>",
      description: "哈囉大家～我很喜歡交朋友也很會聊天 無聊都可以找我出去！超級喜歡戶外活動 爬山排球什麼的 很希望能透過這個學聯認識更多朋友",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 13,
      url: require("../../assets/images/13.png"),
      school: "School:  University of Maryland, College Park",
      major: "Major: Accounting",
      song: "Favorite Song:   美秀集團<心悶>",
      description: "嗨！大家好，我是Justin。是新任的財務組長，很高興能夠為各位服務。雖然目前TSA有些拮据，但還是希望能夠盡可能幫助各位，為各位遠赴異地的同學朋友們能夠有一個互相交流協助的平台。我挺喜歡滑雪的，歡迎喜歡滑雪或是想要一起滑雪的朋友可以一起交流XD",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 14,
      url: require("../../assets/images/14.png"),
      school: "School:  American University",
      major: "Major: Data Science",
      song: "Favorite Song:   守夜人<我睡不著>",
      description: "大家好我是美宣! 目前是碩士新生，喜歡攝影、看動漫或是追劇，也喜歡登山露營，初來乍到還有許多事情等我挖掘，加入學聯會也讓我更快速熟悉這邊的人事物，歡迎大家一起來參與!",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 15,
      url: require("../../assets/images/15.png"),
      school: "School:  George Washington University",
      major: "Major: Business Analytics",
      song: "Favorite Song:   滅火器<島嶼天光>",
      description: "大家好，我來自中壢，GWU MSBA畢業，目前在DC WFH，喜歡戶外活動，希望可以透過學聯幫助辛苦在異鄉奮鬥的台灣人！",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 16,
      url: require("../../assets/images/16.png"),
      school: "School:  American University",
      major: "Major: Data Science",
      song: "Favorite Song:   方大同<特別的人>",
      description: "哈摟大家好！喜歡一切奇奇怪怪也新鮮的事物",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    // {
    //   id: 17,
    //   url: require("../../assets/images/crop34.png"),
    //   school: "School:  University of North Carolina at Chapel Hill",
    //   major: "Major: Economics",
    //   song: "Favorite Song:   林俊傑 <當你>",
    //   description: "很開心成為學聯的一份子！希望大家能多多關注愛護參與學聯的活動",
    //   tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    // }, 
    // {
    //   id: 18,
    //   url: require("../../assets/images/crop36.png"),
    //   school: "School:  Duke University",
    //   major: "Major: MMCi",
    //   song: "Favorite Song:   ABAO阿爆_阿仍仍 <Thank You>",
    //   description: "我剛到美國的時候常常覺得有各種侷限跟困難，但是漸漸發現改變自己心態，其實是自己設下限制，讓很多可能性消失了，希望未來跟所有團隊的成員都可以一起放開心胸來完成所有任務！",
    //   tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    // },   
    // {
    //   id: 19,
    //   url: require("../../assets/images/crop38.png"),
    //   school: "School:  William & Mary",
    //   major: "Major: Accounting",
    //   song: "Favorite Song:   Tanya Chua <Letting Go>",
    //   description: "希望透過大華府學聯能與更多留美台灣學生交流",
    //   tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    // },
    // {
    //   id: 20,
    //   url: require("../../assets/images/crop40.png"),
    //   school: "School:  North Carolina State University",
    //   major: "Major: Computer Science",
    //   song: "Favorite Song:   周杰倫 <白色風車>",
    //   description: "Hi 大家好， 我是Leo,目前在NCSU 讀Master of CS, 很高興能擔任這次的財務組長和認識更多志同道合的朋友， 希望大家能互相扶持成長~",
    //   tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    // },
  ];