export const items = [
    {
      id: 1,
      url: require("../../assets/images/crop2.png"),
      school: "School:  American University",
      major: "Major: Public Policy",
      song: "Favorite Song:   張懸<玫瑰色的你>",
      description: "平常喜歡摸摸人家的貓狗、宅在家裡和朋友吃鍋，也喜歡和 (ㄙㄨㄥˇㄩㄥˇ) 大家一起參加/舉辦有意思的活動XD 然後最近被很多人提醒要運動，歡迎大家揪我養成好習慣 很開心能有這個難得的機會，與廣佈12州區的大家重建學聯～對學聯的未來期許是帶給台灣學子們溫暖和能量並延續下去❤️",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 2,
      url: require("../../assets/images/crop4.png"),
      school: "School:  George Washington University",
      major: "Major: Public Health Nutrition",
      song: "Favorite Song:   李宗盛<鬼迷心竅>",
      description: "哈囉！！我是台中人，很喜歡打排球跟爬山～學聯對我來說是個意義非凡的組織，不僅是一個學生與其他校外團體的橋樑，同時也是學校與學校間連結的管道，很榮幸能參與構築學聯的過程，期待這裡成為一個資源共享的平台，讓出國在外的我們更加團結！",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 3,
      url: require("../../assets/images/crop6.png"),
      school: "School:  The Catholic University of America ",
      major: "Major: Computer Science",
      song: "Favorite Song:   五月天<2012>",
      description: "感謝各位對大華府學聯的關注，希望大家能夠踴躍參加大華府學聯的活動！",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 4,
      url: require("../../assets/images/crop8.png"),
      school: "School:  George Mason University",
      major: "Major: Ph.D. in Education",
      song: "Favorite Song:   莫文蔚<盛夏的果實>",
      description: "喜歡旅行, 交朋友。",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 5,
      url: require("../../assets/images/crop10.png"),
      school: "School:  Duke University",
      major: "Major: Master of Management in Clinical Informatics",
      song: "Favorite Song:   張懸<無狀態>",
      description: "Jenny is a radiation oncologist who has more than 5 years of experience in clinical oncology. She is enthusiastic about advancing medicine through novel medications and technologies. With her Ph.D. candidacy in artificial intelligence and her expertise in connecting hospital professionals with industry representatives, she can identify and support innovative healthcare solutions. Apart from her work, Jenny enjoys practicing and teaching yoga and cooking Chinese cuisine. She is thrilled to utilize her passion and knowledge to make a positive difference in patient care and healthcare innovation.",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 6,
      url: require("../../assets/images/crop12.png"),
      school: "School:  Johns Hopkins University",
      major: "Major: Pathobiology PhD",
      song: "Favorite Song:   A-Lin <大大的擁抱>",
      description: "目前是沒有平假日之分的實驗室打工人平常的興趣是旅遊、煮飯、烘焙和做實驗（！？）因為當初來到美國受到許多台灣學長姐的照顧，所以希望學聯也可以帶給所有來到異鄉的台灣遊子一點溫暖",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 7,
      url: require("../../assets/images/crop14.png"),
      school: "School:  American University",
      major: "Major: BA Communication Studies/ Marketing",
      song: "Favorite Song:   血肉果汁機 <雲煙>",
      description: "前輔大英文系，今年底畢業來自新北市，喜歡衝浪、模型玩具和音樂AU台灣學生會長，身兼大華府學聯社群媒體經營",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 8,
      url: require("../../assets/images/crop16.png"),
      school: "School:  George Washington University",
      major: "Major: Cybersecurity",
      song: "Favorite Song:   茄子蛋<浪子回頭>",
      description: "Hi，大家好! 我是個科技仔，我希望可以用我所學的技術來幫助未來的同學們，讓大家可以透過學聯的各個管道收集到不同的資訊並且可以互相交流。",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 9,
      url: require("../../assets/images/crop18.png"),
      school: "School:  The University of Maryland, College Park",
      major: "Major: Electrical Computer Engineering",
      song: "Favorite Song:   林宥嘉<說謊>",
      description: "大家好～我叫Daniel，我是馬里蘭碩二ECE學生，我的興趣是拉大提琴，出去玩～有空大家可以多約一起出去走走",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
      out: "https://www.linkedin.com/in/daniel-huang-2468a3155/",
      out_name: "linkIn"
    },
    {
      id: 10,
      url: require("../../assets/images/crop20.png"),
      school: "School:  American University",
      major: "Major: MS Financial Analytics",
      song: "Favorite Song:   陳忻玥 <I'm Alive>",
      description: "很高興能成為學聯的一份子 祝各位在求學的過程中能夠挑戰自我 留下美好的回憶",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 11,
      url: require("../../assets/images/crop22.png"),
      school: "School:  George Mason University",
      major: "Major: Data Analytics",
      song: "Favorite Song:   棉花糖 <馬戲團公約>",
      description: "大家好，我是數據分析碩二生，夏天即將畢業。熱愛滑雪、曾經在歐洲背包流浪一年、也喜歡自己動手做木工下廚整理。\n很高興可以在大華府學聯盡棉薄之力，希望能在各項活動中認識更多台灣同學，一起玩耍！",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 12,
      url: require("../../assets/images/crop24.png"),
      school: "School:  Duke University",
      major: "Major: Biomedical Engineering",
      song: "Favorite Song:   伍佰<愛你一萬年>",
      description: "喜歡旅遊、滑雪、潛水, 最大的夢想是走遍世界每個角落",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 13,
      url: require("../../assets/images/crop26.png"),
      school: "School:  Johns Hopkins University",
      major: "Major: MS. Electrical Engineering",
      song: "Favorite Song:   周杰倫 <稻香>",
      description: "大家好,我是一個喜歡戶外活動的人,我的名字是Kevin. 我喜歡旅遊,因為這個喜好,我常常去到不同的地方,體驗不同的文化和風景.我也喜歡爬山和攀岩等的戶外活動.希望今後可以跟大家參加各種有趣的活動.",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 14,
      url: require("../../assets/images/crop28.png"),
      school: "School:  American University",
      major: "Major: MPA",
      song: "Favorite Song:   告五人 <披星戴月的想你>",
      description: "我是以琳，我喜歡旅遊，喜歡攝影，喜歡走走看看嘗試新的事物",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 15,
      url: require("../../assets/images/crop30.png"),
      school: "School:  Johns Hopkins University Bloomberg School of Public Health",
      major: "Major: MHS Social Factors in Health",
      song: "Favorite Song:   蔡依林 <親愛的對像 Untitled>",
      description: "Hello大家好我是許莉翎 Linda 也可以叫我ㄌㄌ 平常最喜歡找好吃的食物＆好拍的景點 所以請記得參加學聯的活動 因為我會盡可能塞進好吃好玩的東西 我還有一個Youtube Channel 歡迎訂閱按讚開啟小鈴鐺 https://www.youtube.com/@itsss_ll",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 16,
      url: require("../../assets/images/crop32.png"),
      school: "School:  Georgia Tech",
      major: "Major: BS Computer Science",
      song: "Favorite Song:   五月天 <終結孤單>",
      description: "大家好我是 Andrew 我喜歡打球 喜歡看漫畫 也喜歡台灣 ",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 17,
      url: require("../../assets/images/crop34.png"),
      school: "School:  University of North Carolina at Chapel Hill",
      major: "Major: Economics",
      song: "Favorite Song:   林俊傑 <當你>",
      description: "很開心成為學聯的一份子！希望大家能多多關注愛護參與學聯的活動",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    }, 
    {
      id: 18,
      url: require("../../assets/images/crop36.png"),
      school: "School:  Duke University",
      major: "Major: MMCi",
      song: "Favorite Song:   ABAO阿爆_阿仍仍 <Thank You>",
      description: "我剛到美國的時候常常覺得有各種侷限跟困難，但是漸漸發現改變自己心態，其實是自己設下限制，讓很多可能性消失了，希望未來跟所有團隊的成員都可以一起放開心胸來完成所有任務！",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },   
    {
      id: 19,
      url: require("../../assets/images/crop38.png"),
      school: "School:  William & Mary",
      major: "Major: Accounting",
      song: "Favorite Song:   Tanya Chua <Letting Go>",
      description: "希望透過大華府學聯能與更多留美台灣學生交流",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 20,
      url: require("../../assets/images/crop40.png"),
      school: "School:  North Carolina State University",
      major: "Major: Computer Science",
      song: "Favorite Song:   周杰倫 <白色風車>",
      description: "Hi 大家好， 我是Leo,目前在NCSU 讀Master of CS, 很高興能擔任這次的財務組長和認識更多志同道合的朋友， 希望大家能互相扶持成長~",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
  ];