export const allstates = [
    {
      id: 1,
      src: require("../../assets/images/crop2.png"),
      school: "WashingtonDC",
      major: "Major: Public Policy",
      song: "Favorite Song:   張懸<玫瑰色的你>",
      description: "平常喜歡摸摸人家的貓狗、宅在家裡和朋友吃鍋，也喜歡和 (ㄙㄨㄥˇㄩㄥˇ) 大家一起參加/舉辦有意思的活動XD 然後最近被很多人提醒要運動，歡迎大家揪我養成好習慣 很開心能有這個難得的機會，與廣佈12州區的大家重建學聯～對學聯的未來期許是帶給台灣學子們溫暖和能量並延續下去❤️",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 2,
      src: require("./images/md.jpg"),
      school: "Maryland",
      major: "Major: Computer Science",
      song: "Favorite Song:   周杰倫 <白色風車>",
      description: "Hi 大家好， 我是Leo,目前在NCSU 讀Master of CS, 很高興能擔任這次的財務組長和認識更多志同道合的朋友， 希望大家能互相扶持成長~",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 3,
      src: require("../../assets/images/crop2.png"),
      school: "Virginia",
      major: "Major: Public Policy",
      song: "Favorite Song:   張懸<玫瑰色的你>",
      description: "平常喜歡摸摸人家的貓狗、宅在家裡和朋友吃鍋，也喜歡和 (ㄙㄨㄥˇㄩㄥˇ) 大家一起參加/舉辦有意思的活動XD 然後最近被很多人提醒要運動，歡迎大家揪我養成好習慣 很開心能有這個難得的機會，與廣佈12州區的大家重建學聯～對學聯的未來期許是帶給台灣學子們溫暖和能量並延續下去❤️",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 4,
      src: require("../../assets/images/crop40.png"),
      school: "WestVirginia",
      major: "Major: Computer Science",
      song: "Favorite Song:   周杰倫 <白色風車>",
      description: "Hi 大家好， 我是Leo,目前在NCSU 讀Master of CS, 很高興能擔任這次的財務組長和認識更多志同道合的朋友， 希望大家能互相扶持成長~",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 5,
      src: require("../../assets/images/crop2.png"),
      school: "NorthCarolina",
      major: "Major: Public Policy",
      song: "Favorite Song:   張懸<玫瑰色的你>",
      description: "平常喜歡摸摸人家的貓狗、宅在家裡和朋友吃鍋，也喜歡和 (ㄙㄨㄥˇㄩㄥˇ) 大家一起參加/舉辦有意思的活動XD 然後最近被很多人提醒要運動，歡迎大家揪我養成好習慣 很開心能有這個難得的機會，與廣佈12州區的大家重建學聯～對學聯的未來期許是帶給台灣學子們溫暖和能量並延續下去❤️",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 6,
      src: require("../../assets/images/crop40.png"),
      school: "SouthCarolina",
      major: "Major: Computer Science",
      song: "Favorite Song:   周杰倫 <白色風車>",
      description: "Hi 大家好， 我是Leo,目前在NCSU 讀Master of CS, 很高興能擔任這次的財務組長和認識更多志同道合的朋友， 希望大家能互相扶持成長~",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 7,
      src: require("../../assets/images/crop2.png"),
      school: "Georgia",
      major: "Major: Public Policy",
      song: "Favorite Song:   張懸<玫瑰色的你>",
      description: "平常喜歡摸摸人家的貓狗、宅在家裡和朋友吃鍋，也喜歡和 (ㄙㄨㄥˇㄩㄥˇ) 大家一起參加/舉辦有意思的活動XD 然後最近被很多人提醒要運動，歡迎大家揪我養成好習慣 很開心能有這個難得的機會，與廣佈12州區的大家重建學聯～對學聯的未來期許是帶給台灣學子們溫暖和能量並延續下去❤️",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 8,
      src: require("../../assets/images/crop40.png"),
      school: "Florida",
      major: "Major: Computer Science",
      song: "Favorite Song:   周杰倫 <白色風車>",
      description: "Hi 大家好， 我是Leo,目前在NCSU 讀Master of CS, 很高興能擔任這次的財務組長和認識更多志同道合的朋友， 希望大家能互相扶持成長~",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 9,
      src: require("../../assets/images/crop2.png"),
      school: "Kentucky",
      major: "Major: Public Policy",
      song: "Favorite Song:   張懸<玫瑰色的你>",
      description: "平常喜歡摸摸人家的貓狗、宅在家裡和朋友吃鍋，也喜歡和 (ㄙㄨㄥˇㄩㄥˇ) 大家一起參加/舉辦有意思的活動XD 然後最近被很多人提醒要運動，歡迎大家揪我養成好習慣 很開心能有這個難得的機會，與廣佈12州區的大家重建學聯～對學聯的未來期許是帶給台灣學子們溫暖和能量並延續下去❤️",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 10,
      src: require("../../assets/images/crop40.png"),
      school: "Tennessee",
      major: "Major: Computer Science",
      song: "Favorite Song:   周杰倫 <白色風車>",
      description: "Hi 大家好， 我是Leo,目前在NCSU 讀Master of CS, 很高興能擔任這次的財務組長和認識更多志同道合的朋友， 希望大家能互相扶持成長~",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 11,
      src: require("../../assets/images/crop2.png"),
      school: "Delaware",
      major: "Major: Public Policy",
      song: "Favorite Song:   張懸<玫瑰色的你>",
      description: "平常喜歡摸摸人家的貓狗、宅在家裡和朋友吃鍋，也喜歡和 (ㄙㄨㄥˇㄩㄥˇ) 大家一起參加/舉辦有意思的活動XD 然後最近被很多人提醒要運動，歡迎大家揪我養成好習慣 很開心能有這個難得的機會，與廣佈12州區的大家重建學聯～對學聯的未來期許是帶給台灣學子們溫暖和能量並延續下去❤️",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 12,
      src: require("../../assets/images/crop40.png"),
      school: "Alabama",
      major: "Major: Computer Science",
      song: "Favorite Song:   周杰倫 <白色風車>",
      description: "Hi 大家好， 我是Leo,目前在NCSU 讀Master of CS, 很高興能擔任這次的財務組長和認識更多志同道合的朋友， 希望大家能互相扶持成長~",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
  ];